export const DEFAULT_KNOWLEDGE_BASE = `FEE REFERENCE DATA (use when students ask about fees — all figures are approximate, always recommend a counselor call for exact current rates):

RUSSIA — 6-Year Total Cost (Tuition + Hostel, approx. INR):
Budget (under 22L): Ingush State Univ 16.5L | Ivanovo State Medical Academy 20L | Kalmyk State Univ 21L | Krasnoyarsk State Medical Univ 21L | Kemerovo State Univ 21L | Chuvash State Medical Univ 21L | Petrozavodsk State Univ 21L | Chechen State Univ 21.5L | Crimea Federal Univ 21.5L | Amur State Medical Univ 21.5L | Kirov State Medical Univ 21.5L | Chita State Medical Academy 22L | Rayzan State Medical Univ 22L
Affordable (22–26L): Kabardino Balkarian State Medical 22L | Orel State Medical Univ 22L | Rostov State Medical Univ 22L | Astrakhan State Univ 22.5L | Sevastopol State Univ 22.5L | Kemerovo State Medical Univ 23L | Immanuel Kant Baltic Federal 23L | Pitrim Sorokin Syktyvkar 23L | Omsk State Medical Univ 23.5L | North Caucasian State Medical 24L | Northern Ossetian State Medical Academy 24L | Yaroslov the Wise Novgorod State Univ 24L | SP Petersburg State Pediatric Medical Univ 24.5L | Northern State Medical Univ 24.5L | Dagestan State Medical Univ 25L | Izhevsk State Medical Academy 25L | Tambov State Univ 25L | Pskov State Univ 25.5L | Bashkir State Medical Univ 26L | Stavropol State Medical Univ 26L | Ulyanovsk State Medical Univ 26L | Yaroslavl State Medical Univ 26L
Mid-range (27–32L): Lobachevsky State Medical Univ 27L | Altai State Medical Univ 28L | Belgorod State Medical Univ 28L | Irkutsk State Medical Univ 28.5L | Siberian State Medical Univ 28.5L | Voronezh State Medical Univ 29L | Mari State Univ 30L | Mordovia State Univ 30.5L | Pacific State Medical Univ 30L | Samara State Medical Univ 30L | Kuban State Medical Univ 31L | Tyumen State Medical Univ 31.5L | North Western State Medical Univ 32.5L | Privolzhsky Research Medical Univ 32.5L | Tula State Medical Univ 32L | Tver State Medical Univ 32L
Premium (33L+): Far Eastern Federal Univ 33L | ME PHI Obninsk 33.5L | Synergy Univ 33.5L | Volgograd State Medical Univ 34.9L | Kazan State Medical Univ 36L | Orenburg State Medical Univ 36L | Perm State Medical Univ 36L | Novosibirsk State Univ 36.5L | Saratov State Medical Univ 36.5L | Kazan Federal Univ 38L | National Research Nuclear MEPHI Moscow 42L | Pavlov First State SPB Medical Univ 44L | Lomonosov Moscow State Univ 50L | Pirogov Russian National Research Medical Univ 50L | Peoples Friendship Univ 52.5L | IM Sechenov First Moscow State Medical Univ 70L
Russia overall range: 16.5L–70L. Most popular affordable range: 21L–32L. OTC for most: ~1200 USD one-time. Mess: 1200–1500 USD/year where applicable (some universities include it).

UZBEKISTAN — 6-Year Total, ALL-INCLUSIVE (Tuition + Hostel + Mess + Visa + PR + Medical):
Gulistan State Univ: 24L | Angren University: 24L | Tashkent Medical Academy Urgench Branch: 26L | Bukhara State Medical Univ: 28L | Termez Branch Tashkent Medical Academy: 28L | Andijan State Medical Univ: 30L | Samarkand State Medical Univ: 30L ← FLAGSHIP RECOMMENDATION | Fergana Medical Institute of Public Health: 30L | Tashkent Pharmaceutical Institute: 30L | Tashkent State Medical Univ: 31L
Uzbekistan range: 24L–31L fully all-inclusive (no hidden costs). Samarkand State Medical Univ is the top recommendation — large Indian student community, excellent university, safe city, very affordable.

HOW TO USE THIS DATA:
If student says budget is "20–25L": suggest Uzbekistan (Gulistan 24L, Angren 24L, Bukhara 28L) and budget Russia options (Ingush 16.5L, Ivanovo 20L, Chuvash 21L).
If student says budget is "25–35L": Samarkand Uzbekistan (30L, all-inclusive, best value) and mid-range Russia options.
If student says budget is "35L+": premium Russian universities and Tashkent State Medical Univ.
Always lead with Uzbekistan (especially Samarkand) as the best value option if budget allows 28L+.
Never quote exact figures as guaranteed — always add "approximately" and recommend counselor call for exact rates.`;
